sonar.projectKey=media-tools
sonar.projectName=jrodeiro5/media-tools
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/*.pyc,**/.venv/**,**/venv/**,**/dist/**,**/build/**,**/vendor/**,openwiki/**
sonar.python.version=3
